# Site settings
title: Dr. Qing-Yuan Jiang
email: qyjiang24@gmail.com
description: Personal webpage of Dr. Qing-Yuan Jiang
baseurl: ""
url: ""
affiliation: I am ... <a href="https://www.google.com" target="_blank">...</a> ....

# # Google analytics ID
# google_analytics: G-7BE63RZMTW

# # Location info. (shown in footer)
# location: >
#   Department of Industrial Design<br/>
#   P.O. Box 513<br/>
#   5600 MB Eindhoven<br/>
#   Netherlands<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: <a href="mailto:qyjiang24@gmail.com" target="_blank">qyjiang24@gmail.com</a><br/>

# Pages shown in navbar
nav_pages:
  - name: about
  # - name: publications
  # - name: talks
  # - name: research
  # - name: education
  # - name: volunteering

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

collections:
  courses:
    output: true
  publications:
    output: true
  workshops:
    output: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
